include:
  - component: $CI_SERVER_FQDN/idw/pipeline-catalog/website-javadoc-uploader-component@0.0.2
    inputs: 
      stage: publish
      target_branch: main

image: $PLUGIN_BUILDER_IMAGE

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.

stages:
  - build_reporting
  - publish

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_SUBMODULE_STRATEGY: recursive
  DEFAULT_BRANCH_ROOT_URL: "$CI_PROJECT_URL/-/blob/$CI_DEFAULT_BRANCH"
  
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export GIT_SSH_COMMAND=/usr/bin/ssh
  - git checkout "$CI_COMMIT_REF_NAME"
  - export JAVA_HOME=$JAVA_11
  - set_java_version
  - get_iiq_binaries ./lib/sailpoint/ identityiq connector-bundle-identityiq

build:
  stage: build_reporting
  script: 
    - ./gradlew build javadoc -x checkstyleMain -x checkstyleTest
  artifacts:
    name: "iiqcommon-public-library"
    paths:
      - build/docs/**
      - build/libs/**
      - build/reports/**
    # expire_in: 1 month

checkstyle:
  stage: build_reporting
  script:
    - ./gradlew checkstyleMain
  artifacts:
    name: "checkstyle"
    reports:
      codequality:
        - build/reports/checkstyle/main.json

deploy:
  stage: publish
  needs:
    - job: build
      artifacts: true
  script:
    - ./gradlew publish
    # Trigger website javadoc update
    # - curl --request POST --form "variables[PROJECT_ID]=$CI_PROJECT_ID" --form "variables[BRANCH]=$CI_COMMIT_BRANCH" --form "variables[JOB_NAME]=build" "$CI_SERVER_URL/api/v4/projects/197/trigger/pipeline?token=$CI_JOB_TOKEN&ref=main"

  rules:
    - if: $CI_COMMIT_BRANCH == "main"