= IIQ Common Public Repository
:toc:

== Introduction

This repository contains a "minimal" subset of IDW's broader IIQCommon library. These utilities do not represent the full power of IIQCommon, but they should be sufficient to make IIQ development easier.

== Maven repository

Updates to the `main` branch in this repository are pushed to our hosted GitLab's Maven package repository. You can set up this repository in your `pom.xml` using the following configuration:

[source,xml]
----
<repositories>
  <repository>
    <id>gitlab-maven</id>
    <url>https://git.identityworksllc.com/api/v4/projects/157/packages/maven</url>
  </repository>
</repositories>

<distributionManagement>
  <repository>
    <id>gitlab-maven</id>
    <url>https://git.identityworksllc.com/api/v4/projects/157/packages/maven</url>
  </repository>

  <snapshotRepository>
    <id>gitlab-maven</id>
    <url>https://git.identityworksllc.com/api/v4/projects/157/packages/maven</url>
  </snapshotRepository>
</distributionManagement>
----

Or Gradle repository configuration:

[source,groovy]
----
maven {
  url 'https://git.identityworksllc.com/api/v4/projects/157/packages/maven'
}
----

The Maven coordinates for the library are:

* Group ID: `com.identityworksllc.iiq.common.minimal`
* Artifact ID: `iiq-common-public`
* Version: A non-semver date string in the format `yyyyMM.dd.HHmmss` (e.g., `202310.03.170641`)

== Building the library

=== JDK version

You can build this library with JDK 8, JDK 11, or JDK 17.

The code style is consistent with JDK 8 so that the library will be compatible with existing IIQ installations.

=== Supplying the IIQ dependencies

IDW cannot distribute SailPoint's proprietary binaries, so you must supply them yourself.

Insert the following JAR files from your IIQ version in the `lib/sailpoint` folder. (These files can be found in any IIQ WAR file at `WEB-INF/lib`.)

* identityiq.jar
* connector-bundle-identity.jar

=== Library JAR build

To build the library, execute `./gradlew build`. (On Windows, use `gradlew.bat build` instead.)

The library will be assembled at `build/libs/iiq-common-public-<version>.jar`. For deployment into your environment, you may want to manually remove the version tag so that you can always update the file in place.

=== Javadocs

You can assemble the Javadocs for this library using the `./gradlew javadoc` command. The Javadocs will be rendered using the link:https://github.com/mnlipp/jdrupes-mdoclet[mdoclet] library.

Files will be output to `build/docs/javadoc`.

== Utilities included

TODO: Expand this section