= IIQ Common Public Repository
:toc:

== Introduction

IIQCommon is a utility library used in virtually all of our SailPoint IdentityIQ installations and plugins. This is the ever-expanding open source portion of this library, published under the Apache License 2.0. Feel free to create an account https://git.identityworksllc.com/pub/iiqcommon[on our Gitlab] to report issues or submit pull requests.

This repository is also https://github.com/instrumental-id/iiq-common-public[mirrored to Github.com].

https://instrumentalidentity.com/javadoc/iiq-common-public/index.html[Library Javadocs may be accessed at any time on Instrumental ID's site.]

== Maven repository

Updates to the `main` branch in this repository are pushed to our hosted GitLab's Maven package repository. You can set up this repository in your `pom.xml` using the following configuration:

[source,xml]
----
<repositories>
  <repository>
    <id>gitlab-maven</id>
    <url>https://git.identityworksllc.com/api/v4/projects/157/packages/maven</url>
  </repository>
</repositories>

<distributionManagement>
  <repository>
    <id>gitlab-maven</id>
    <url>https://git.identityworksllc.com/api/v4/projects/157/packages/maven</url>
  </repository>

  <snapshotRepository>
    <id>gitlab-maven</id>
    <url>https://git.identityworksllc.com/api/v4/projects/157/packages/maven</url>
  </snapshotRepository>
</distributionManagement>
----

Or Gradle repository configuration:

[source,groovy]
----
maven {
  url 'https://git.identityworksllc.com/api/v4/projects/157/packages/maven'
}
----

The Maven coordinates for the library are:

* Group ID: `com.identityworksllc.iiq.common.minimal`
* Artifact ID: `iiq-common-public`
* Version: A non-semver date string in the format `yyyyMM.dd.HHmmss` (e.g., `202310.03.170641`)

== Releases

Certain releases will be forked into branches. These will receive backports of significant bug fixes, but are not expected to receive major new functionality. Furthermore, these releases are intended to be stable against a target JDK and a target IIQ version. 

* `release/2024.10.07`: Stable with JDK 8 and IIQ 8.1 through 8.4.

== Building the library

=== JDK version

You can build this library with JDK 11 or JDK 17.

Beginning with 2026 releases, the library will be built with JDK 11 and will require JDK 11 or later to run.

=== Supplying the IIQ dependencies

IDW cannot distribute SailPoint's proprietary IIQ binaries, so you must supply them yourself.

Insert the following JAR files from your IIQ version in the `lib/sailpoint` folder. (These files can be found in any IIQ WAR file at `WEB-INF/lib`.)

* identityiq.jar
* connector-bundle-identity.jar

=== Library JAR build

To build the library, execute `./gradlew build`. (On Windows, use `gradlew.bat build` instead.)

The library will be assembled at `build/libs/iiq-common-public-<version>.jar`. For deployment into your environment, you may want to manually remove the version tag so that you can always update the file in place.

=== Javadocs

You can assemble the Javadocs for this library using the `./gradlew javadoc` command. The Javadocs will be rendered using the link:https://github.com/mnlipp/jdrupes-mdoclet[mdoclet] library.

Files will be output to `build/docs/javadoc`.

== Utilities included

TODO: Expand this section