= ThingAccessUtils

The *ThingAccessUtils* class is responsible for making an authorization decision based on a configuration, a subject identity, and an optional target identity. It is available in the '-public' IIQCommon JAR.

== APIs

You may invoke any of the `checkThingAccess` methods in *ThingAccessUtils*.

NOTE: All of the API variants require a `BasePluginResource` for extracting the caller context and other information. If you are invoking this utility from some other context, you can use `ThingAccessUtils.createFakePluginContext` to create a mock context for passing to these methods.

If you desire more full-featured output, you should construct an `AccessCheckInput` object, providing the parameters. When you invoke that API method, the `AccessCheckResponse` will contain more details about which checks passed and failed.

== Configuration objects

Options may be specified as either a `Map`, with these identifiers as the keys, or as a `CommonSecurityConfig` object.

Access control options, in order of evaluation, are:

* `disabled`: If set to `true`, access is denied for all users.
* `oneOf`: Contains a nested list of Common Security maps and allows access if any spec in the list allows access.
* `allOf`: Contains a nested list of Common Security maps and allows access if all of the specs in the list allow access.
* `not`: Contains a single nested Common Security map and inverts it. Allows access only if the nested spec does *not* allow access.
* `settingOffSwitch`: If the given plugin setting is _true_, access is not allowed for any user.
* `accessCheckScript`: If the given Beanshell script returns boolean _true_, access is allowed. Otherwise, access is denied. The script will be passed an _identity_ (the target identity being viewed) and _requester_ (the subject identity doing the viewing).
* `accessCheckRule`: If the specified Beanshell Rule returns boolean _true_, access is allowed. Otherwise, access is denied. The Rule will be passed an _identity_ (the target identity being viewed) and _requester_ (the subject identity doing the viewing).
* `requiredRights`: Access is allowed if the subject user has _any_ of the listed SPRights.
* `excludedRights`: Access is allowed if the subject user has _none_ of the listed SPRights.
* `requiredCapabilities`: Access is allowed if the subject user has _any_ of the listed Capabilities.
* `excludedCapabilities`: Access is allowed if the subject user has _none_ of the listed Capabilities.
* `requiredWorkgroups`: Access is allowed if the subject user is in _any_ of the listed workgroups.
* `excludedWorkgroups`: Access is allowed if the subject user is in _none_ of the listed workgroups.
* `accessCheckSelector`: Access is allowed if the subject user matches the given IdentitySelector. This is where you would specify a Filter for access control, for example.
* `mirrorQuicklinkPopulation`: Access is allowed if the combination of subject user and target user would be allowed by the given QuickLink Population.
* `validTargetExcludedRights`: Access is allowed if the target user _does not_ have any of the listed SPRights.
* `validTargetExcludedCapabilities`: Access is allowed if the target user _does not_ have any of the listed Capabilities.
* `invalidTargetFilter`: Access is allowed if the action _target_ *does not* match the filter string.
* `validTargetWorkgroups`: Access is allowed if the action _target_ is a member of any of the listed workgroups.
* `validTargetCapabilities`: Access is allowed if the action _target_ is assigned any of the listed capabilities.
* `validTargetSelector`: Access is allowed if the action _target_ matches the given selector.
* `validTargetFilter`: Access is allowed if the action _target_ matches the given filter string.


=== Subject and target identities

The _subject user_ or _requester_ is the person who is logged into the UI, using a plugin feature. If Sam is viewing Bob's identity page, Sam is the _subject_ and Bob is the _target_. Controls that would apply to Bob will have "Target" in the name, such as "validTargetFilter". Other controls would apply to Sam.

Some access checks (e.g., to see if a certain user can receive notifications) don't have the concept of a target. In those cases, the access check is run with the same Identity (Sam, in the example) as _both_ subject and target.

=== Short-circuiting

If any particular access check results in a _deny_ response, restrictions farther down the list will not be evaluated. A message will be logged at DEBUG level (if enabled) indicating which check failed to pass.

=== Access check Beanshell is authoritative

If an `accessCheckScript` or `accessCheckRule` is provided, a non-null output is considered authoritative and final. Further restrictions are not evaluated. A null result will continue to restrictions farther down the list.

=== Error handling

If any check throws an exception, access is _denied_ and the exception logged.

=== Empty configuration

If _no_ restrictions are specified, access is _allowed_ by default.

== Caching

By default, *ThingAccessUtils* results will be cached for 60 seconds. The cache key is a combination of the input configuration, the subject identity ID, and the target identity ID.

To manually clear the cache (e.g., from Beanshell), you may invoke `ThingAccessUtils.clearCachedResults()`.

== Metadata

Access restriction objects also have two metadata fields:

* `description`: A verbal description of the restrictions, used for human consumption only at this time.
* `noCache`: If present and set to _true_, access check results will not be cached.